inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

# Allow 'Pokémon-style' exception handling
Lint/RescueException:
  Enabled: false

# Disable all metrics.
Metrics:
  Enabled: false

# REVIEW: Only 2 offenses if enabled, is there a rationale for this?
# Allow CamelCase constants as well as SCREAMING_SNAKE_CASE
Naming/ConstantName:
  Enabled: false

# Ignore `eval` in the examples folder
Security/Eval:
  Exclude:
    - examples/*

# https://stackoverflow.com/q/4763121/
Style/Alias:
  Enabled: false

# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

# So RuboCop doesn't complain about application IDs
Style/NumericLiterals:
  Exclude:
    - examples/*

# Prefer |m, e| for the `reduce` block arguments
Style/SingleLineBlockParams:
  Methods:
    - reduce: [m, e]
    - inject: [m, e]
