# Disable all metrics.
Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

# Allow CamelCase constants as well as SCREAMING_SNAKE_CASE
Style/ConstantName:
  Enabled: false

# Allow 'Pokémon-style' exception handling
Lint/RescueException:
  Enabled: false

# Prefer |m, e| for the `reduce` block arguments
Style/SingleLineBlockParams:
  Methods:
    - reduce: [m, e]
    - inject: [m, e]

AllCops:
  TargetRubyVersion: 2.2

# https://stackoverflow.com/q/4763121
Style/Alias:
  Enabled: false

# So RuboCop doesn't complain about application IDs
Style/NumericLiterals:
  Exclude:
    - examples/*

# Ignore `eval` in the examples folder
Security/Eval:
  Exclude:
    - examples/*
