require: rubocop-performance

inherit_mode:
  merge:
    - AllowedNames

AllCops:
  TargetRubyVersion: 2.4

# Allow 'Pokémon-style' exception handling
Lint/RescueException:
  Enabled: false

# Disable all metrics.
Metrics:
  Enabled: false

# Allow some common and/or obvious short method params
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - e

# Ignore `eval` in the examples folder
Security/Eval:
  Exclude:
    - examples/**/*

# https://stackoverflow.com/q/4763121/
Style/Alias:
  Enabled: false

# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

# So RuboCop doesn't complain about application IDs
Style/NumericLiterals:
  Exclude:
    - examples/**/*

# Prefer |m, e| for the `reduce` block arguments
Style/SingleLineBlockParams:
  Methods:
    - reduce: [m, e]
    - inject: [m, e]
